### PR TITLE
Changed the title issue

### LINKED ISSUE #216: Bug Report: Incorrect Error Message for Month Field in Monthly Check-In Submission Form
**Describe the bug**

In the new Monthly Check-In submission form, the first input field is labeled "Month." However, when the user attempts to submit an empty form, the field displays the error message "Title is required." This message should instead display "Month is required."
 
**To Reproduce**
1. Go to the Mentee Dashboard
2. Click on the "Submit Your Monthly Check-In" button.
3. Scroll to the bottom and click Submit without entering any data.
4. Observe the error message.

**Expected behavior**
The error message "Title is required" should instead display "Month is required."

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3
 - Browser: Chromium 
 - Version: 129.0.6668.100

**Smartphone (please complete the following information):**

**Additional context**

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by KavinduGama**
## Purpose

The purpose of this PR is to fix #216 

## Goals
Changes the authentication error

## Approach
Changed the string on schema.ts

##  Checklist
- [ ] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: src/schemas.ts [hunk 1]
```diff
@@ -124,7 +124,7 @@ export const MentorApplicationSchema = z.object({
 });
 
 export const MenteeCheckInSchema = z.object({
-  title: z.string().min(1, 'Title is required'),
+  title: z.string().min(1, 'Month is required'),
```
Comment (anjula-sack) [inline src/schemas.ts]:
```suggestion
  month: z.string().min(1, 'Month is required'),
```
Change the field as well

**Review by anjula-sack — CHANGES_REQUESTED** [review]

**Review by anjula-sack — APPROVED** [review]
Thank you! @KavinduGama
