### PR TITLE
Change the Breadcrumb names into one  line on mobile view

### LINKED ISSUE #177: Breadcrumb names split into two lines on mobile view
**Describe the bug**
In the mobile view of the ScholarX application, on the mentee public profile page, long names in the breadcrumb navigation are splitting into two lines, causing a formatting issue and potentially affecting readability.

**To Reproduce**
1. Open the ScholarX application on a mobile device
2. Click on Find a mentor from the nav bar
3. Select a mentor with some mentees in progress.
4. Click on a mentee to navigate to a mentee profile page with long names in the breadcrumb (e.g., Stephany Ernser > Grace Wiegand)
5. Observe that the names in the breadcrumb split into two lines

**Expected behavior**
The breadcrumb should display all names on a single line, potentially with a truncation or alternative solution to handle long names without line breaks.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS  - Browser: Not specified 
 - Version: Not specified

**Additional context**

**Are you working on it?**
No

### PR DESCRIPTION
**Pull request by Sanjana0823**
## Purpose

The purpose of this PR is to fix #177 

## Goals

- The breadcrumb should display all names on a single line

## Approach

- Change `text-sm`  to `text-xs sm:text-sm md:text-base` that the text size will be xs (extra small) on mobile screens, change to sm (small) on small screens (640px and above), and increase to base (normal size) on medium screens (768px and above).

## Screenshots

image

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

File: src/pages/MenteeProfile/MenteeProfile.component.tsx [hunk 1]
```diff
@@ -13,8 +13,25 @@ const MenteeProfile: React.FC = () => {
...
+              <ChevronRightIcon />
+            </Link>
+          </button>
+          <Link
+            to={`/mentors/${mentee?.mentor.uuid ?? ''}`}
+            className="block transition hover:text-gray-700 md:hidden ml-2"
+          >
+            Back
+          </Link>
+        </div>
```
Comment (anjula-sack) [inline src/pages/MenteeProfile/MenteeProfile.component.tsx]:
```suggestion
<div className="flex items-center">
          <Link
            to={`/mentors/${mentee?.mentor.uuid ?? ''}`}
            className="flex items-center transition hover:text-gray-700 md:hidden"
          >
            <span className="transform rotate-180"><ChevronRightIcon  /></span>
            <span className="ml-2">Back</span>
          </Link>
        </div>
```

**Review by anjula-sack — APPROVED** [review]
Good job! @Sanjana0823

**Comment by Sanjana0823** [comment]
> Good job! @Sanjana0823

Thank you @anjula-sack
